// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddModelValidation3Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModelValidation3Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201309181935328_AddModelValidation3Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
